language: node_js
node_js:
  - "stable"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email:
  - xdenser@gmail.com  
before_install:
  - sudo add-apt-repository ppa:mapopa/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq firebird2.5-superclassic firebird2.5-dev
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
  - sudo service firebird2.5-superclassic start
  - npm install nodeunit
before_script:
  - cd build
  - mkdir test_db
  - cd test_db
  - sudo isql-fb -input ../../tests/createTestDB.sql
  - sudo chmod 0666 TEST.FDB
  - cd ../..

