language: node_js
node_js:
  - "stable"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email:
  - xdenser@gmail.com  
before_install:
  - sudo add-apt-repository ppa:mapopa/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes firebird2.5-superclassic firebird2.5-dev
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
  - sudo service firebird2.5-superclassic start
  - sudo cat /etc/firebird/2.5/SYSDBA.password
  - sudo bash -c '(export FB_VER="2.5"; export FB_FLAVOUR="superclassic";source /usr/share/firebird2.5-common/functions.sh; writeNewPassword masterkey)'
  - sudo cat /etc/firebird/2.5/SYSDBA.password
  - npm install nodeunit
  - sleep 5
before_script:
  - cd build
  - mkdir test_db
  - cd test_db
  - sudo isql-fb -input ../../tests/createTestDB.sql
  - sudo chmod -c 0777 TEST.FDB
  - sudo chmod -Rc a+x /home/travis/build/xdenser/node-firebird-libfbclient/build/test_db
  - ls -l
  - cd ../..

